// ============================================================
//  main.js — reads CONFIG, builds the page
//  Do not edit this file per client.
// ============================================================

document.addEventListener('DOMContentLoaded', () => {

  // 1. Apply theme
  const s = document.documentElement.style;
  s.setProperty('--primary',   CONFIG.theme.primary);
  s.setProperty('--secondary', CONFIG.theme.secondary);
  s.setProperty('--accent',    CONFIG.theme.accent);
  s.setProperty('--dark',      CONFIG.theme.dark);
  s.setProperty('--cream',     CONFIG.theme.cream);
  s.setProperty('--text',      CONFIG.theme.text);
  s.setProperty('--muted',     CONFIG.theme.muted);
  s.setProperty('--border',    CONFIG.theme.border);

  // 2. Restaurant name & meta
  document.querySelectorAll('[data-name]').forEach(el => el.textContent = CONFIG.restaurant.name);
  document.querySelectorAll('[data-tagline]').forEach(el => el.textContent = CONFIG.restaurant.tagline);
  document.title = CONFIG.restaurant.name + ' · Café & Restaurant';

  // 3. Hero image
  const heroImg = document.getElementById('hero-bg-img');
  if (CONFIG.images.hero && heroImg) { heroImg.src = CONFIG.images.hero; heroImg.alt = CONFIG.restaurant.name; }

  // 4. Build sections
  buildLocationsBanner();
  buildMenu();
  buildAbout();
  buildContact();

  // 5. Sticky nav
  const nav = document.querySelector('nav');
  window.addEventListener('scroll', () => nav.classList.toggle('scrolled', window.scrollY > 60));

  // 6. Mobile menu
  document.getElementById('hamburger').addEventListener('click', () => document.getElementById('mobile-menu').classList.add('open'));
  document.getElementById('mobile-close').addEventListener('click', () => document.getElementById('mobile-menu').classList.remove('open'));
  document.querySelectorAll('#mobile-menu a').forEach(a => a.addEventListener('click', () => document.getElementById('mobile-menu').classList.remove('open')));

  // 7. Scroll reveal
  initReveal();
});

// ---- Locations Banner ----
function buildLocationsBanner() {
  const row = document.getElementById('locations-row');
  CONFIG.locations.forEach((loc, i) => {
    if (i > 0) {
      const div = document.createElement('span');
      div.className = 'locations-divider';
      div.textContent = '·';
      row.appendChild(div);
    }
    const pill = document.createElement('div');
    pill.className = 'location-pill';
    pill.innerHTML = `📍 <strong>${loc.name}</strong> ${loc.address.split(',')[0]} &nbsp;<a href="${loc.googleMaps}" target="_blank" rel="noopener">Get directions →</a>`;
    row.appendChild(pill);
  });
}

// ---- Menu ----
function buildMenu() {
  const categoriesEl = document.getElementById('menu-categories');
  const panelsEl = document.getElementById('menu-panels');

  CONFIG.menu.forEach((cat, i) => {
    // Card
    const card = document.createElement('div');
    card.className = 'category-card reveal';
    card.dataset.index = i;
    card.innerHTML = `
      <div class="category-bg" style="background:${cat.gradient}">
        ${cat.cover ? `<img src="${cat.cover}" alt="${cat.category}" loading="lazy" onerror="this.style.display='none'">` : ''}
      </div>
      <div class="category-overlay"></div>
      <div class="category-info">
        <div class="category-name">${cat.category}</div>
        <div class="category-desc">${cat.description}</div>
      </div>
      <div class="category-badge">Open ✓</div>
    `;
    card.addEventListener('click', () => togglePanel(i));
    categoriesEl.appendChild(card);

    // Panel
    const panel = document.createElement('div');
    panel.className = 'menu-panel';
    panel.id = `panel-${i}`;
    panel.innerHTML = `
      <div class="panel-header">
        <div class="panel-title">${cat.category}</div>
        <div class="panel-count">${cat.items.length} items</div>
      </div>
      <div class="menu-items">
        ${cat.items.map(item => `
          <div class="menu-item">
            <div class="item-name">${item.name}</div>
            <div class="item-desc">${item.description}</div>
          </div>
        `).join('')}
      </div>
    `;
    panelsEl.appendChild(panel);
  });

  togglePanel(0); // open first by default
}

function togglePanel(index) {
  document.querySelectorAll('.category-card').forEach((c, i) => c.classList.toggle('active', i === index));
  document.querySelectorAll('.menu-panel').forEach((p, i) => p.classList.toggle('active', i === index));
  if (window.innerWidth < 768) {
    setTimeout(() => document.getElementById('menu-panels').scrollIntoView({ behavior: 'smooth', block: 'nearest' }), 100);
  }
}

// ---- About ----
function buildAbout() {
  const img = document.getElementById('about-img');
  if (CONFIG.images.about && img) { img.src = CONFIG.images.about; img.alt = CONFIG.restaurant.name; }

  document.getElementById('about-text').textContent = CONFIG.restaurant.about;

  // Stats
  const statsEl = document.getElementById('about-stats');
  CONFIG.stats.forEach(stat => {
    const div = document.createElement('div');
    div.innerHTML = `<div class="stat-number">${stat.number}</div><div class="stat-label">${stat.label}</div>`;
    statsEl.appendChild(div);
  });

  // Instagram link
  const igEl = document.getElementById('about-ig');
  if (CONFIG.social.instagram && igEl) {
    igEl.href = CONFIG.social.instagram;
    igEl.style.display = 'inline-flex';
  }
}

// ---- Contact ----
function buildContact() {
  // Location cards
  const locGrid = document.getElementById('locations-grid');
  CONFIG.locations.forEach(loc => {
    const card = document.createElement('div');
    card.className = 'location-card reveal';
    card.innerHTML = `
      <div class="location-card-header">
        <div class="location-card-name">${loc.name} Location</div>
        <div class="location-tag">${loc.name}</div>
      </div>
      <div class="location-card-body">
        <div class="location-detail">
          <span class="location-detail-icon">📍</span>
          <div>
            <div class="location-detail-label">Address</div>
            <div class="location-detail-value">${loc.address}</div>
          </div>
        </div>
        <div class="location-detail">
          <span class="location-detail-icon">📞</span>
          <div>
            <div class="location-detail-label">Phone</div>
            <div class="location-detail-value">${loc.phone}</div>
          </div>
        </div>
        <a class="location-maps-btn" href="${loc.googleMaps}" target="_blank" rel="noopener">
          🗺️ &nbsp; Open in Google Maps
        </a>
      </div>
    `;
    locGrid.appendChild(card);
  });

  // Hours strip
  document.getElementById('hours-text').innerHTML = `<strong>⏰ Hours:</strong> ${CONFIG.restaurant.hours}`;

  // Delivery buttons
  const deliveryEl = document.getElementById('delivery-buttons');
  CONFIG.delivery.forEach(d => {
    const a = document.createElement('a');
    a.href = d.url;
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
    a.className = 'delivery-btn';
    a.innerHTML = `<span class="delivery-emoji">${d.emoji}</span><span>${d.name}</span><span class="delivery-arrow">→</span>`;
    deliveryEl.appendChild(a);
  });

  // Footer Instagram
  const footerIg = document.getElementById('footer-ig');
  if (footerIg && CONFIG.social.instagram) {
    footerIg.href = CONFIG.social.instagram;
    footerIg.style.display = 'inline';
  }
}

// ---- Scroll Reveal ----
function initReveal() {
  const obs = new IntersectionObserver(entries => {
    entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target); } });
  }, { threshold: 0.1 });
  document.querySelectorAll('.reveal').forEach(el => obs.observe(el));
}
